package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.DockerSupportFeature
import jetbrains.buildServer.configs.kotlin.buildFeatures.dockerRegistryConnections
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAndPublish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAndPublish")) {
    features {
        val feature1 = find<DockerSupportFeature> {
            dockerRegistryConnections {
                loginToRegistry = on {
                    dockerRegistryId = "PROJECT_EXT_163"
                }
            }
        }
        feature1.apply {
            loginToRegistry = on {
                dockerRegistryId = "PROJECT_EXT_163,PROJECT_EXT_147"
            }
        }
    }
}
