{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" . }}-secret
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "app.name" . }}-secret
  data:
    {{- range .Values.externalSecret.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ printf "%s/%s/%s" $.Values.externalSecret.ssmPathPrefix (include "app.name" $) .remoteRef }}
    {{- end }}
{{- end }}
