{{- if and (not .Values.secret.existingSecret) (not .Values.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-secret
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.secret.authSecret | quote }}
{{- end }}
