apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
