apiVersion: ecr.aws.m.upbound.io/v1beta1
kind: Repository
metadata:
  name: ${IMAGE_NAME}
  namespace: app-${APP_NAME}
  annotations:
    crossplane.io/external-name: ${APP_NAME}
spec:
  forProvider:
    imageTagMutability: MUTABLE
    region: ap-southeast-2
