apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secret
  namespace: app-${APP_NAME}
  labels:
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/component: secret
type: Opaque
data:
  API_SECRET_KEY: "c3VwZXJzZWNyZXRrZXkxMjM="
  AUTH_SECRET: "cmVwbGFjZS10aGlzLWFwcC1zZWNyZXQ="