apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_NAME}-sa
  namespace: app-${APP_NAME}
  labels:
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/component: serviceaccount
  annotations:
    techlab.techlab.example.com/app: ${APP_NAME}
automountServiceAccountToken: true
